name = "PartialFunctions"
uuid = "570af359-4316-4cb7-8c74-252c00c2016b"
authors = ["Thomas Marks <marksta@umich.edu> and contributors"]
version = "1.2.1"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
MacroTools = "0.5"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
